## --------------------------------------------------------------------------
## run_variant.tcl, project-03
##
## Runs the full synthesis -> implementation -> post-implementation timing
## simulation (SAIF activity dump) -> report export flow for a single
## architectural variant, at a given clock period.
##
## Usage:
##   vivado -mode batch -source scripts/project-03/run_variant.tcl \
##       -tclargs <variant_name> [clk_period_ns]
##
## Examples:
##   vivado -mode batch -source scripts/project-03/run_variant.tcl -tclargs baseline
##   vivado -mode batch -source scripts/project-03/run_variant.tcl -tclargs registering 10.0
##   vivado -mode batch -source scripts/project-03/run_variant.tcl -tclargs reordering 5.5
##
## Recommended invocation (captures the console/simulation log for the
## Python notebook's STEP 1 functional-check parsing):
##   vivado -mode batch \
##       -log notebooks/output/project-03/sims/reports/<variant>/vivado_console_<clk_period_ns>ns.log \
##       -source scripts/project-03/run_variant.tcl -tclargs <variant> <clk_period_ns>
##
## Outputs (under notebooks/output/project-03/sims/reports/<variant>/):
##   utilization.rpt, timing_summary.rpt, power.rpt, activity.saif
##
## HOW THE CLOCK PERIOD IS APPLIED (fixed after a real run surfaced two
## errors: `if` is not a supported command in XDC files, and `launch_runs`
## spawns synthesis/implementation in a context that does NOT share this
## script's Tcl global variables -- so a Tcl-variable-based constraint,
## read from the XDC itself, can never work):
##   res/srcs/project-03/vivado_constrs/top.xdc holds a static, literal
##   `create_clock -period <value> ...` line. This script REWRITES that
##   literal value directly on disk, before every synthesis run, to match
##   the requested clk_period_ns. Synthesis always re-reads the constraint
##   file fresh from disk, so this reliably applies per run.
##
## HOW THE SAIF ACTIVITY FILE IS GENERATED (adopted from a working manual
## GUI flow: Settings > Simulation > Simulation > xsim.simulate.saif /
## xsim.simulate.saif_all_signals, rather than this script's original
## manual open_saif/log_saif/close_saif, which produced a SAIF that
## matched 0/666 design nets):
##   the sim fileset properties xsim.simulate.saif and
##   xsim.simulate.saif_all_signals are set before launch_simulation, so
##   xsim dumps a fully-populated SAIF automatically, at Vivado's own
##   default path under the project's .sim run directory -- no manual
##   open_saif/log_saif calls needed.
##
## ASSUMPTIONS (flagged pending STEP 1 / testbench deliverable):
##   - res/srcs/project-03/vivado_tbs/tb_top.vhd exists (entity tb_top,
##     architecture sim) and self-terminates the simulation (VHDL-2008
##     std.env.stop), so `run -all` completes without an explicit
##     sim_time argument.
##   - `report_power` has NO `-saif`/`-saif_scope` option, and `read_saif`
##     has NO `-scope` option (both confirmed via `report_power -help` /
##     `read_saif -help` against a real Vivado install): activity is
##     loaded via a plain `read_saif <path>` call (no -strip_path), which
##     matches the working manual flow -- once the SAIF is generated via
##     the fileset-property method above, the default hierarchy handling
##     correlates nets correctly.
## --------------------------------------------------------------------------

# --- Arguments --------------------------------------------------------------
if {[llength $argv] < 1} {
    error "Usage: run_variant.tcl <variant_name> \[clk_period_ns\]"
}
lassign $argv variant_name clk_period_ns

if {$clk_period_ns eq ""} { set clk_period_ns 10.0 }

# --- Paths --------------------------------------------------------------
# This script lives at <repo_root>/scripts/project-03/, two levels below
# the repo root.
set script_dir [file normalize [file dirname [info script]]]
set repo_root  [file normalize [file join $script_dir ".." ".."]]

set sims_dir       [file join $repo_root "notebooks" "output" "project-03" "sims"]
set project_root   [file join $sims_dir "vivado_project"]
set reports_root   [file join $sims_dir "reports"]
set xpr_path       [file join $project_root "project-03.xpr"]
set xdc_path       [file join $repo_root "res" "srcs" "project-03" "vivado_constrs" "top.xdc"]

source [file join $script_dir "variants.tcl"]

# --- Rewrite the clock constraint's literal period on disk -----------------
# See the header note above: this MUST be a literal value written into the
# actual .xdc file, not a Tcl variable reference evaluated inside it.
set xdc_fh [open $xdc_path w]
puts $xdc_fh "## Auto-generated by run_variant.tcl -- do not edit by hand."
puts $xdc_fh "## Rewritten before every synthesis run to match the requested clk_period_ns."
puts $xdc_fh "create_clock -period $clk_period_ns -name clk \[get_ports clk\]"
close $xdc_fh
puts "INFO: clk_period_ns = $clk_period_ns (written to $xdc_path)"

# --- Open (or bootstrap) the project ---------------------------------------
if {[file exists $xpr_path]} {
    open_project $xpr_path
} else {
    puts "INFO: project-03.xpr not found, bootstrapping via create_project.tcl"
    source [file join $script_dir "create_project.tcl"]
}

# --- Select variant ----------------------------------------------------
set variant_info [select_variant $variant_name]
lassign $variant_info top_entity vhd_file report_subfolder sim_configuration pipeline_latency
set report_folder "${report_subfolder}_${clk_period_ns}"

set reports_dir [file join $reports_root $report_folder]
file mkdir $reports_dir

# --- Helper: abort on run failure --------------------------------------------
proc check_run_status {run_name} {
    set status [get_property STATUS [get_runs $run_name]]
    if {[string match -nocase "*error*" $status] || [string match -nocase "*failed*" $status]} {
        error "$run_name failed (status: $status). Check the run log before re-running."
    }
    puts "INFO: $run_name completed (status: $status)"
}

# --- Synthesis --------------------------------------------------------------
reset_run synth_1
launch_runs synth_1 -jobs 4
wait_on_run synth_1
check_run_status synth_1

# --- Implementation -----------------------------------------------------
reset_run impl_1
launch_runs impl_1 -jobs 4
wait_on_run impl_1
check_run_status impl_1

open_run impl_1

# --- Utilization and timing reports (from the implemented design) -----------
report_utilization    -file [file join $reports_dir "utilization.rpt"]
report_timing_summary -file [file join $reports_dir "timing_summary.rpt"] -max_paths 10

# --- Post-implementation timing simulation: SAIF activity dump --------------
# Fileset-property-driven generation (validated manually): xsim writes the
# SAIF itself, with full signal coverage, to a fixed default path under the
# project's own .sim run directory.
set saif_filename "activity.saif"

set_property -name {xsim.simulate.saif}             -value $saif_filename -objects [get_filesets sim_1]
set_property -name {xsim.simulate.saif_all_signals} -value {true}        -objects [get_filesets sim_1]

launch_simulation -mode post-implementation -type timing -simset [get_filesets sim_1]
run -all
close_sim

set saif_path [file join $project_root "project-03.sim" "sim_1" "impl" "timing" "xsim" $saif_filename]

if {![file exists $saif_path]} {
    error "Expected SAIF not found at $saif_path -- check the simulation log \
           for xsim.simulate.saif / xsim.simulate.saif_all_signals errors."
}

# --- Power report, using the post-implementation activity dump --------------
open_run impl_1
set_load 5 [all_outputs]
read_saif $saif_path
report_power -file [file join $reports_dir "power.rpt"] -xpe [file join $reports_dir "power.xpe"]

# Keep a copy of the SAIF alongside the other reports for traceability.
file copy -force $saif_path [file join $reports_dir "activity.saif"]

puts "INFO: variant '$variant_name' @ ${clk_period_ns}ns done. \
      Reports written to $reports_dir"
